- name: install staff
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - epel-release
    - python
    - python-pip
    - curl
    - wget
    - sudo

- name: Install for mysql
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - PyMySQL
    - cryptography
  when: inventory_hostname == "db_tier"

- name: Esure Ansible Facts Dir exists
  become: yes
  file: path=/etc/ansible/facts.d state=directory recurse=yes

- name: sudoers
  become: yes
  lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults'
    line: 'Defaults        !requiretty'
